#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
	/config/www

# copy config
[[ $(find /config/www -type f | wc -l) -eq 0 ]] && \
	cp /defaults/index.html /config/www/index.html
[[ ! -f /config/Caddyfile ]] && \
	cp /defaults/Caddyfile /config/Caddyfile

# fetch site
[[ ! -d /config/www/Dashboard/.git ]] && \
git clone https://github.com/causefx/Organizr /config/www/organizr/

# permissions
chown -R abc:abc /config