#!/usr/bin/with-contenv bash
# make our folders
mkdir -p \
	/config/www

# copy config
[[ $(find /config/www -type f | wc -l) -eq 0 ]] && \
	cp /defaults/index.html /config/www/index.html
[[ ! -f /config/Caddyfile ]] && \
	cp /defaults/Caddyfile /config/Caddyfile

if [[ ! -d /config/www/Dashboard/.git ]]; then
  echo '-----------------------'
  echo '| Installing Organizr |'
  echo '-----------------------'
  git clone -b v2-develop https://github.com/causefx/Organizr /config/www/organizr
elif [[ -d /config/www/Dashboard/.git ]]; then
  echo '-----------------------'
  echo '|  Updating Organizr  |'
  echo '-----------------------'
  cd /config/www/organizr || return
  git reset --hard origin/v2-develop
  git pull --rebase
fi

# fix permisions on php-frm
sed -i 's/user = nobody/user = abc/g' /etc/php7/php-fpm.d/www.conf
sed -i 's/group = nobody/group = abc/g' /etc/php7/php-fpm.d/www.conf

# permissions
chown -R abc:abc /config
