#!/usr/bin/with-contenv bash
# make our folders
mkdir -p \
	/config/www

# copy config
[[ $(find /config/www -type f | wc -l) -eq 0 ]] && \
	cp /defaults/index.html /config/www/index.html
[[ ! -f /config/Caddyfile ]] && \
	cp /defaults/Caddyfile /config/Caddyfile

# fetch site
[[ ! -d /config/www/organizr/.git ]] && \
git clone -b v2-develop --single-branch https://github.com/causefx/Organizr /config/www/organizr
#git clone https://github.com/causefx/Organizr /config/www/organizr/

# fix permisions on php-frm
sed -i 's/user = nobody/user = abc/g' /etc/php7/php-fpm.d/www.conf
sed -i 's/group = nobody/group = abc/g' /etc/php7/php-fpm.d/www.conf

# permissions
chown -R abc:abc /config
